### ISSUE TITLE
What's working and Not working.

### ISSUE THREAD

**Issue by ZeroShadowX** [CryptoNeverSleeps/DELL-XPS-7590-OLED#1]
My apologies if you noted this but I don't see it anywhere. I am thinking about purchasing this laptop were you able to figure out Brightness Control, Touch Screen Controls and HDMI out? I know you mentioned Sleep to Wake wasn't working but just wanted to check. Knowing these will help in my decision.

Thanks for your hard work.

**Comment by CryptoNeverSleeps** [comment]
This is the OLED Model which is not Touchscreen:   Use this or other EFI's for that...    - just search XPS 7590 on Github.....

https://github.com/shadowed87/Hackintosh-XPS-7590:

Everything is working except Brightness Control and Black screen when waking from sleep.  I have not tested HDMI Out... 

This is another link with OLED model... more notes and (Issues - Resolved / Unresolved)...

The 4K Touch Screen Model is not OLED.

https://github.com/geek5nan/Hackintosh-XPS7590
